Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 632, in initialize
    self.init_sockets()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 287, in init_sockets
    self.stdin_port = self._bind_socket(self.stdin_socket, self.stdin_port)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 229, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 205, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/zmq/sugar/socket.py", line 214, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[31mWARNING: /home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md
Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 147, in execute
    None,
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 158, in execute_single
    allow_errors=allow_errors,
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/client.py", line 542, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/client.py", line 501, in async_setup_kernel
    await self.async_start_new_kernel_client()
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/client.py", line 428, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/jupyter_client/client.py", line 180, in _async_wait_for_ready
    raise RuntimeError("Kernel died before replying to kernel_info")
RuntimeError: Kernel died before replying to kernel_info[39;49;00m
[31mWARNING: Couldn't find cache key for notebook file content/annotation.md. Outputs will not be inserted.[39;49;00m
[91m/home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md.rst:122: WARNING: Couldn't find key `table_cogat_forms` in keys defined across all pages.[39;49;00m
[91m/home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md.rst:180: WARNING: Couldn't find key `figure_cogat_expansion` in keys defined across all pages.[39;49;00m
[91m/home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md.rst:256: WARNING: Couldn't find key `table_lda` in keys defined across all pages.[39;49;00m
[91m/home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md.rst:316: WARNING: Couldn't find key `table_gclda` in keys defined across all pages.[39;49;00m
[91m/home/data/nbc/misc-projects/Salo_NiMARE/content/annotation.md.rst:357: WARNING: Couldn't find key `figure_gclda_topics` in keys defined across all pages.[39;49;00m
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_NiMARE/conda_env/lib/python3.7/site-packages/nbclient/client.py", line 369, in _async_cleanup_kernel
    assert self.km is not None
AssertionError
