[91mWARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://nimare.readthedocs.io/en/0.0.10/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='nimare.readthedocs.io', port=443): Max retries exceeded with url: /en/0.0.10/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0cbea9fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))[39;49;00m
[91mWARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://pymare.readthedocs.io/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='pymare.readthedocs.io', port=443): Max retries exceeded with url: /en/latest/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0cbec22d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))[39;49;00m
